services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    environment:
      - NODE_ENV=production
      - PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
